version: '2'
services:
    src:
        build : ./docker/php
        volumes:
            - .:/var/www/html
            - ./docker/php/config:/usr/local/etc/php/conf.d
            - ~/.composer:/root/.composer
        working_dir: /var/www/html

    db:
        image: mysql:5.5
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test

    tests:
        extends:
            service: src
        links:
            - db
        command: ./vendor/bin/phpunit

    composer:
        extends:
            service: src
        command: composer install -o -n
